### PR TITLE
enhance warning: networks, network config, volume config. Fixes #88, #71

### LINKED ISSUE #88: Wrong warning about networks
wrong warning about networks not supported, even if networks not provided: `WARN[0000] Unsupported key networks - ignoring`

using `docker-compose.yml`
```yaml
$ cat docker-compose.yml 
version: "2"

services:
  redis:
    image: dharmit/redis
    command: redis-server
    ports:
      - "6379"
    volumes:
      - /opt/redis:/redis

  flask:
    image: dharmit/flask
    ports:
      - "31000:5000"
    depends_on:
      - redis
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
```

Output
```yaml
$ kompose convert --stdout -f docker-compose.yml -y
WARN[0000] Unsupported key depends_on - ignoring        
WARN[0000] Unsupported key networks - ignoring          
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
```

### PR DESCRIPTION
**Pull request by ngtuna**
@janetkuo : I added warning for `volume config` and `network config`.
@surajssd : `networks` key is checked. However, please take a look at [FIXME](https://github.com/ngtuna/kompose/blob/unsupported-keys/cli/app/app.go#L869) and leave me your thought.

### CODE REVIEW

**Comment by ngtuna** [comment]
Fixes #75 as well

**Comment by surajssd** [comment]
Nice LGTM!

**Comment by ngtuna** [comment]
Thanks @surajssd . It needs one more `+1` from @janetkuo to get the PR merged :wink:

File: cli/app/app.go [hunk 1]
```diff
@@ -854,8 +854,25 @@ func loadComposeFile(file string, opt convertOptions) KomposeObject {
 
 	// transform composeObject into komposeObject
 	composeServiceNames := composeObject.ServiceConfigs.Keys()
+
+	// volume config and network config has not supported
```
Comment (janetkuo) [inline cli/app/app.go]: typo: *are* not supported

File: cli/app/app.go [hunk 2]
```diff
@@ -1165,9 +1182,9 @@ func Convert(c *cli.Context) {
 func checkUnsupportedKey(service interface{}) {
 	s := structs.New(service)
 	for _, f := range s.Fields() {
-		if f.IsExported() && !f.IsZero() {
+		if f.IsExported() && !f.IsZero() && strings.Compare(f.Name(), "Networks") != 0 {
```
Comment (janetkuo) [inline cli/app/app.go]: `f.Name() != "Networks"`

File: cli/app/app.go [hunk 3]
```diff
@@ -854,8 +854,25 @@ func loadComposeFile(file string, opt convertOptions) KomposeObject {
...
+	if len(composeObject.VolumeConfigs) > 0 {
+		logrus.Warningf("Unsupported volume configuration of compose v2 - ignoring")
+	}
+
+	count := 0
 	for _, name := range composeServiceNames {
 		if composeServiceConfig, ok := composeObject.ServiceConfigs.Get(name); ok {
+			//FIXME: networks always contains one default element, even it isn't declared in compose v2.
+			if len(composeServiceConfig.Networks.Networks) > 0 &&
+				strings.Compare(composeServiceConfig.Networks.Networks[0].Name, "default") != 0 &&
```
Comment (janetkuo) [inline cli/app/app.go]: `composeServiceConfig.Networks.Networks[0].Name != "default"`

File: cli/app/app.go [hunk 4]
```diff
@@ -854,8 +854,25 @@ func loadComposeFile(file string, opt convertOptions) KomposeObject {
...
+				count == 0 {
+				logrus.Warningf("Unsupported key networks - ignoring")
+				count++
```
Comment (janetkuo) [inline cli/app/app.go]: How about instead of `count`, use something like `found bool` or `networksWarningFound bool`?

File: cli/app/app.go (hunk 3 above)
Comment (janetkuo) [inline cli/app/app.go]: But users can configure their default network https://docs.docker.com/compose/networking/#/configuring-the-default-network and we should give them warnings for that too

Comment (janetkuo) [inline cli/app/app.go]: Perhaps we can print different warnings for default networks (may be set implicitly) vs. custom networks

Comment (janetkuo) [inline cli/app/app.go]: If there's only default networks, warn that the default networks isn't supported; if there's default and/or custom networks, warn that networks isn't supported

File: cli/app/app.go (hunk 2 above)
Comment (ngtuna) [inline cli/app/app.go]: what is the main benefit of replacing `strings.Compare()` with `!=` to compare strings?

File: cli/app/app.go (hunk 3 above)
Comment (ngtuna) [inline cli/app/app.go]: With the sample of default network as below, I see the message still makes sense:

```console
$ cat default-network.yml
version: '2'

services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres

networks:
  default:
    # Use a custom driver
    driver: custom-driver-1
$ kompose convert --file default-network.yml
WARN[0000] Unsupported network configuration of compose v2 - ignoring 
WARN[0000] Unsupported key build - ignoring             
WARN[0000] [db] Service cannot be created because of missing port. 
file "web-svc.json" created
file "db-deployment.json" created
file "web-deployment.json" created
```
I appreciate your idea of detailing messages. But with default or custom network, from my viewpoint, I see the message `unsupported key networks` is still good. So if voting, I am 0.

File: cli/app/app.go (hunk 2 above)
Comment (kadel) [inline cli/app/app.go]: `!=` makes this much more easier to read.
Also [docs](https://golang.org/pkg/strings/#Compare) says: "Compare is included only for symmetry with package bytes. It is usually clearer and always faster to use the built-in string comparison operators ==, <, >, and so on."

**Comment by ngtuna** [comment]
@janetkuo: I added a `fixing-typos` commit. I'm gonna merge this PR for accelerating the progress. If we test and find somehow the networks warning is still not good enough (as you mentioned the case of default/custom network above), we can always open issue for that.
